### ISSUE TITLE
Perfect mod for me, but need some balance

### ISSUE THREAD

**Issue by Terzief** [sbtoonz/GreatSwords#1]
Can you add please settings for swords damage? Its too high in my opinion, or at least explain how I can change values by myself?

**Comment by sbtoonz** [comment]
resolved by f9700c1

**Comment by sbtoonz** [comment]
https://valheim.thunderstore.io/package/sbtoonz/Great_Swords/

**Comment by sbtoonz** [comment]
should note you gotta clear your old cfg files so you can let it render new ones with the item configuration
